server:
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=prodhib
    username: postgres
    password: Asdfg6hj
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      current_session_context_class: thread

